name: Apply Patches

on: [push]

jobs:
  apply-patches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Apply patches
        run: ./apply-patches.sh
